# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

black_tea = Category.create(name: "Black Tea", description: "Black tea is a type of tea that is more oxidized than oolong, yellow, white and green teas. Black tea is generally stronger in flavor than other teas. All four types are made from leaves of the shrub (or small tree) Camellia sinensis. Two principal varieties of the species are used – the small-leaved Chinese variety plant (C. sinensis var. sinensis), used for most other types of teas, and the large-leaved Assamese plant (C. sinensis var. assamica), which was traditionally mainly used for black tea, although in recent years some green and white teas have been produced. In China, where black tea was developed,[1] the beverage is called red tea, due to the color of the oxidized leaves when processed appropriately.[1]", img_url: "https://www.t2tea.com/on/demandware.static/-/Library-Sites-T2SharedLibrary/default/dw947c93c9/images/content/tea-landing-type-black.jpg", instructions: "temp: 100 degrees | water: 250mL | amount: 1 tsp | time: 3 mins")

green_tea = Category.create(name: "Green Tea", description: "Green tea is a type of tea that is made from Camellia sinensis leaves and buds that have not undergone the same withering and oxidation process used to make oolong teas and black teas.[1] Green tea originated in China, but its production and manufacture has spread to other countries in East Asia.
Several varieties of green tea exist, which differ substantially based on the variety of C. sinensis used, growing conditions, horticultural methods, production processing, and time of harvest. Although there has been considerable research on the possible health effects of consuming green tea regularly, there is little evidence that drinking green tea has any effects on health.[2]", img_url: "https://www.t2tea.com/on/demandware.static/-/Library-Sites-T2SharedLibrary/default/dw931d93aa/images/content/tea-landing-type-green.jpg", instructions: "temp: 80 degrees | water: 250ml | amount: 1 tsp | time: 2 mins")

white_tea = Category.create(name: "White Tea", description: "White tea may refer to one of several styles of tea which generally feature young or minimally processed leaves of the Camellia sinensis plant.
Currently there is no generally accepted definition of white tea and very little international agreement; some sources use the term to refer to tea that is merely dried with no additional processing,[1] some to tea made from the buds and immature tea leaves picked shortly before the buds have fully opened and allowed to wither and dry in natural sun,[citation needed] while others include tea buds and very young leaves which have been steamed or fired before drying.[2] Most definitions agree, however, that white tea is not rolled or oxidized[citation needed], resulting in a flavor characterized as lighter than most green or traditional black teas.
In spite of its name, brewed white tea is pale yellow. Its name derives from the fine silvery-white hairs on the unopened buds of the tea plant, which give the plant a whitish appearance.[3] The unopened buds are used for some types of white tea.
It is harvested primarily in China, mostly in the Fujian province,[4] but more recently produced in Eastern Nepal, Taiwan, Thailand, Galle (Southern Sri Lanka) and northeast India.", img_url: "https://www.t2tea.com/on/demandware.static/-/Library-Sites-T2SharedLibrary/default/dwce3893d9/images/content/tea-landing-type-white.jpg", instructions: "temp: 70 degrees | water: 250ml | amount: 1.5 tsp | time: 2 mins")

oolong_tea = Category.create(name: "Oolong Tea", description: "Oolong tea is a traditional semi-oxidized Chinese tea (Camellia sinensis) produced through a process including withering the plant under strong sun and oxidation before curling and twisting.[1] Most oolong teas, especially those of fine quality, involve unique tea plant cultivars that are exclusively used for particular varieties. The degree of oxidation, which varies according to the chosen duration of time before firing, can range from 8–85%,[2] depending on the variety and production style. Oolong is especially popular in south China and among Chinese expatriates in Southeast Asia[3] as is the Fujian preparation process known as the Gongfu tea ceremony.
Different styles of oolong tea can vary widely in flavor. They can be sweet and fruity with honey aromas, or woody and thick with roasted aromas, or green and fresh with complex aromas, all depending on the horticulture and style of production.[1] ", img_url: "https://www.t2tea.com/on/demandware.static/-/Library-Sites-T2SharedLibrary/default/dwb2b652a1/images/content/tea-landing-type-oolong.jpg", instructions: "temp: 100 degrees | water: 250ml | amount: 1 tsp | time: 3 mins")

herbal_tea = Category.create(name: "Herbal Tea", description: "Herbal teas—less commonly[1] called tisanes are beverages made from the infusion or decoction of herbs, spices, or other plant material in hot water. The term herbal tea is often used in contrast to true teas (e.g., black, green, white, yellow, oolong), which are prepared from the cured leaves of the tea plant, Camellia sinensis. Besides coffee and true teas (which are also available decaffeinated), most tisanes do not contain caffeine.[3]", img_url: "https://www.t2tea.com/on/demandware.static/-/Library-Sites-T2SharedLibrary/default/dw6a4663ad/images/content/tea-landing-type-herbal.jpg", instructions: "temp: 80 degrees | water: 250ml | amount: 1 tsp | time: 2 mins")

chai_tea = Category.create(name: "Chai Tea", description: "Masala chai is a flavoured tea beverage made by brewing black tea with a mixture of aromatic Indian spices and herbs. Originating in the Indian subcontinent,[1][2][3] the beverage has gained worldwide popularity, becoming a feature in many coffee and tea houses. Although traditionally prepared as a decoction of green cardamom pods, cinnamon sticks, ground cloves, ground ginger, and black peppercorn together with black tea leaves, retail versions include tea bags for infusion, instant powdered mixtures, and concentrates.", img_url: "https://www.t2tea.com/on/demandware.static/-/Library-Sites-T2SharedLibrary/default/dw0b533d8f/images/content/tea-landing-type-chai.jpg", instructions: "temp: 50 degrees | water: 240ml | amount: 0.5 tsp | time: 2 mins")



tea1 = Tea.create(name:"Madagascar Green Tea", time: "4", amount: "2", temp: "185", water: "250", notes: "Earthy green tea with a subtle hint of french vanilla.", category_id: green_tea.id)
tea2 = Tea.create(name:"Hunter's Tea", time: "3", amount: "1", temp: "160", water: "220", notes: "Very smooth with a hint of lemon.", category_id: black_tea.id)
tea3 = Tea.create(name:"Christmas Tea", time: "2", amount: "1", temp: "180", water: "200", notes: "Light, buttery, yet fruity.", category_id: white_tea.id)
